blank_issues_enabled: false
contact_links:
  - name: Security Vulnerabillity
    url: https://github.com/RedotOpenGame/game/security/advisories/new
    about: Please report security vulnerabilities here.
    
