extends Area3D
#This code was generated by Claude AI, lol.
const explosion_scene = preload("res://Scenes/meshes/explosion.tscn")
@export var projectile_speed: float = 12.0
@export var arc_height: float = 5.0
@export var damage: float = 15.0
@export var explosion_radius: float = 3.0

var start_position: Vector3
var target_position: Vector3
var journey_length: float
var start_time: float
var is_initialized: bool = false

func _ready():
	# Wait for initialization before starting movement
	set_physics_process(false)

func initialize(target: Vector3):
	start_position = global_position
	target_position = target
	journey_length = start_position.distance_to(target_position)
	start_time = Time.get_ticks_msec() / 1000.0  # Convert to seconds
	is_initialized = true
	set_physics_process(true)

func _physics_process(_delta):
	if not is_initialized:
		return
		
	var current_time = Time.get_ticks_msec() / 1000.0
	var distance_covered = (current_time - start_time) * projectile_speed
	var journey_fraction = distance_covered / journey_length
	# Calculate arc movement
	var current_position = start_position.lerp(target_position, journey_fraction)
	var parabola = sin(journey_fraction * PI) * arc_height
	current_position.y += parabola
	
	if global_position != current_position:
		look_at(current_position) #Except for this.
	
	global_position = current_position
	
	# When projectile reaches target
	if journey_fraction >= 1.0:
		explode()

func explode():
	# Create physics sphere to detect bodies
	var scene = explosion_scene.instantiate()
	scene.position = global_position
	scene.damage = damage
	add_sibling(scene)
	
	# Optional: Add explosion effect
	# var explosion = explosion_scene.instantiate()
	# get_parent().add_child(explosion)
	# explosion.global_position = global_position
	
	# Clean up
	queue_free()

# Optional: Add visual trail
func _process(_delta):
	if is_initialized:
		# You can add trail effect here
		pass
